Up.

diff --git a/bin.symlink/aws-export b/bin.symlink/aws-export
--- a/bin.symlink/aws-export
+++ b/bin.symlink/aws-export
@@ -1,5 +1,13 @@
 #!/bin/bash
 
+EXISTS=$(grep "\[$1\]" ~/.aws/credentials)
+
+if [ -z "$EXISTS" ]
+then
+    echo "Credentials not found."
+    exit 1
+fi
+
 OUT=$(grep "\[$1\]" ~/.aws/credentials -A2 \
     | tail -n2 \
     | sed 's/aws_access_key_id = /export AWS_ACCESS_KEY_ID=/' \
